---
swagger: '2.0'
info:
  description: |-
    # Intro

    This website documents the API methods available for our Discord `TipBot` [here](http://invite.discord.bot.tips/).

    The public API url is [https://public-trade-api.bot.tips/](https://public-trade-api.bot.tips/).

    The private API url is [https://private-api.bot.tips/](https://private-api.bot.tips/).

    # API Wrappers

    To use private API, you need to obtain key by interacting with TipBot's direct message `.acc tradeapi`.

    # Support

    If you are having issues, please stop by our [discord](https://chat.wrkz.work) and visit the `#development` channel for assistance.

  version: 1.0.0
  title: tradeapi-tipbot
tags:
  - name: Public
    description: This call does not require any key
paths:
  /markets:
    get:
      summary: Retrieves information available and opened trading pairs
      tags:
        - Public
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/Markets'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  '/ticker/{coin}':
    get:
      summary: Retrieves information regarding trading information of a coin
      parameters:
        - name: coin
          type: string
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
      tags:
        - Public
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/Info.Coin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  '/orders/{pair}':
    get:
      summary: Retrieves list of buy and sell orders
      parameters:
        - name: pair
          type: string
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
      tags:
        - Public
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/Pair.Coin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'


  '/get_balance/{coin}':
    get:
      summary: Get the balance for a coin
      parameters:
        - name: coin
          type: string
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
      tags:
        - Private Query
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/BalanceCoin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  '/deposit/{coin}':
    get:
      summary: Get a deposit address of a coin
      parameters:
        - name: coin
          type: string
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
      tags:
        - Private Query
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/DepositCoin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'


  '/buy':
    post:
      summary: Buy an opened order with referenced number
      tags:
      - Private Query
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/components/requestBodies/buyBody'

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/Buy'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  '/sell':
    post:
      summary: Buy an opened order with referenced number
      tags:
      - Private Query
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/components/requestBodies/sellBody'

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/Sell'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  '/cancel':
    post:
      summary: Cancel order with referenced number
      tags:
      - Private Query
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/components/requestBodies/buyBody'

      responses:
        '200':
          description: OK
          schema:
            $ref: '#/components/schemas/Cancel'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  requestBodies:
    buyBody:
      description: Buy ref number
      required:
        - ref_number
      properties:
        ref_number:
          type: string
          required: true
          example: 1002222
    sellBody:
      description: Sell parameters
      required:
        - coin_sell
        - coin_get
        - amount_sell
        - amount_get
      properties:
        coin_sell:
          type: string
          description: Coin you want to sell
          required: true
          example: XMR
        coin_get:
          type: string
          description: Coin you want get
          required: true
          example: WRKZ
        amount_sell:
          type: string
          description: Amount of coin to sell
          required: true
          example: 0.001
        amount_get:
          type: string
          description: Amount of coin to get
          required: true
          example: 10,000.00

  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: A parse error occured, or an error occured processing your request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: An exception was thrown whilst processing the request. See the console for logs. Please report.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
      # Schema for error response body
    Error:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
      required:
        - errorCode
        - errorMessage
    Markets:
      properties:
        success:
          type: string
          description: true or false
          example: true
        market_list:
          type: array
          description: Lists of opened markets
          example: ["BAN-DEGO", "BAN-WRKZ", "BTCMZ-BAN", "BTCMZ-GNTL", "BTCMZ-LTC", "BTCMZ-WOW", "BTCMZ-WRKZ", "DEGO-BAN", "DEGO-BTCMZ", "DEGO-DOGE", "DEGO-GNTL", "DEGO-TRTL", "DEGO-WOW", "DEGO-WRKZ", "DEGO-XFG", "DOGE-GNTL", "DOGE-WRKZ", "GNTL-BAN", "GNTL-BTCMZ", "GNTL-LTC"]
        timestamp:
          type: number
          example: 1635582551

    Info.Coin:
      properties:
        success:
          type: string
          description: true or false
          example: true
        volume_24h:
          type: string
          description: Trade volume last 24 hours in string format
          example: >-
            13,274.6637
        volume_7d:
          type: string
          description: Trade volume last 7 days in string format
          example: >-
            130,274.6637
        volume_30d:
          type: string
          description: Trade volume last 30 days in string format
          example: >-
            10,30,274.6637
        markets:
          type: array
          description: Lists of opened markets
          example: ["WRKZ-DOGE", "WRKZ-XMR", "WRKZ-LTC"]
        timestamp:
          type: number
          example: 1635582551

    Pair.Coin:
      properties:
        success:
          type: string
          description: true or false
          example: true
        order_book:
          type: string
          description: pair that you call
          example: >-
            WRKZ-DOGE
        buy_refs:
          type: array
          description: List of ref_numbers
          example: >-
            ["1001111", "1001113", "1001112"]
        buy:
          type: array
          description: Amount and rate
          example: >-
            {"49.00000000": "33333.33336667", "50.00000000":"33333.33336667", "60.00000000":"113333.33336667"}
        sell_refs:
          type: array
          description: List of ref_numbers
          example: >-
            ["1002111", "1002113", "1002112"]
        sell:
          type: array
          description: Amount and rate
          example: >-
            {"49.00000000": "33333.33336667", "50.00000000":"33333.33336667", "60.00000000":"113333.33336667"}
        timestamp:
          type: number
          example: 1635582551

    BalanceCoin:
      properties:
        success:
          type: string
          description: true or false
          example: true
        WRKZ:
          type: array
          description: coin name
          items:
            properties:
              balance:
                type: string
                description: Balance in string format
                example: >-
                  10,000.00
              maintenance:
                type: string
                description: true or false
                example: false

    DepositCoin:
      properties:
        success:
          type: string
          description: true or false
          example: true
        WRKZ:
          type: array
          description: coin name
          items:
            properties:
              deposit_address:
                type: string
                description: Deposit address
                example: >-
                  WrkzReo4ys8HFtoJkWvcEb9bSwQnXUDswAZqXR4A5cBa9PtYm4VS7Uz9w1WkuDquK1J6YXPGb3hrkHw15goxkeBHHxdBTLWnyRQb3X63R46gBBeuxBrgbRZ2qZLRf5TwnheZ1rpta1FAbR7XvMK6bL8Jkk293fJBL2ywDcHCXur4Z8VY59NBQcvwhB
              maintenance:
                type: string
                description: true or false
                example: false

    Buy:
      properties:
        success:
          type: string
          description: true or false
          example: true
        result:
          type: array
          description: coin name
          items:
            properties:
              ref_number:
                type: string
                example: >-
                  1002222
              message:
                type: string
                description: result's message
                example: >-
                  1002222 Order completed! Get: 1,000 WKRZ From selling: 10 DOGE

    Sell:
      properties:
        success:
          type: string
          description: true or false
          example: true
        result:
          type: array
          items:
            properties:
              message:
                type: string
                description: Balance in string format
                example: >-
                  New open order created: #**1002222** Selling: 1,000 GNTL For: 0.0057XMR Fee: 1.000 GNTL

    Cancel:
      properties:
        success:
          type: string
          description: true or false
          example: true
        message:
          type: string
          example: >-
            You cancelled 1002222.
