---
swagger: '2.0'
info:
  description: |-
    # Intro

    This website documents the API methods available for our Discord `TipBot` [here](http://invite.discord.bot.tips/).

    The public API url is [https://public-trade-api.bot.tips/](https://public-trade-api.bot.tips/).

    The private API url is [https://private-api.bot.tips/](https://private-api.bot.tips/).

    # API Wrappers

    To use private API, you need to obtain key by interacting with TipBot's direct message `.acc tradeapi`.

    # Support

    If you are having issues, please stop by our [discord](https://chat.wrkz.work) and visit the `#development` channel for assistance.
  version: 1.0.0
  title: tradeapi-tipbot
tags:
  - name: Public
    description: This call does not require any key
paths:
  /markets:
    get:
      summary: Retrieves information available and opened trading pairs
      tags:
        - Public
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Markets'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  '/ticker/{coin}':
    get:
      summary: Retrieves information regarding trading information of a coin
      parameters:
        - name: coin
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
          schema:
            type: string
      tags:
        - Public
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info.Coin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'

  '/orders/{coin1}-{coin2}':
    get:
      summary: Retrieves list of buy and sell orders
      parameters:
        - name: coin1
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
          schema:
            type: string
        - name: coin2
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
          schema:
            type: string
      tags:
        - Public
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info.Coin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalError'


  '/get_balance/{coin}':
    get:
      summary: Get the balance for every coin
      parameters:
        - name: coin
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
          schema:
            type: string
      tags:
        - Private Query
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balances'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  '/deposit/{coin}':
    get:
      summary: Get a deposit address of a coin
      parameters:
        - name: coin
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
          schema:
            type: string
      tags:
        - Private Query
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Deposit.Coin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'


  '/get_balance/{coin}':
    get:
      summary: Get balance of a coin
      parameters:
        - name: coin
          description: Supported and tradable coin name by TipBot
          in: path
          required: true
          schema:
            type: string
      tags:
        - Private Query
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance.Coin'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

  /buy:
    post:
      summary: Buy an opened order with referenced number
      tags:
        - Private Query
      requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - ref_number
                properties:
                  ref_number:
                    type: string
                    description: Referenced number
                    example: >-
                      1002222
      responses:
        '200':
          description: The operation completed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: true
                  result:
                    type: object
                    property:
                      ref_number:
                        type: string
                        example: >-
                          1002222
                       message:
                        type: string
                        example: >-
                          Order completed!
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'

components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: A parse error occured, or an error occured processing your request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: An exception was thrown whilst processing the request. See the console for logs. Please report.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
      # Schema for error response body
    Error:
      type: object
      properties:
        errorCode:
          type: integer
        errorMessage:
          type: string
      required:
        - errorCode
        - errorMessage
    Markets:
      properties:
        success:
          type: string
          description: true or false
          example: true
        market_list:
          type: object

    Info.Coin:
      properties:
        success:
          type: string
          description: true or false
          example: true
        volume_24h:
          type: string
          description: Trade volume last 24 hours in string format
        volume_7d:
          type: string
          description: Trade volume last 7 days in string format
        volume_30d:
          type: string
          description: Trade volume last 30 days in string format
        markets:
          type: object
          description: Lists of opened markets
    Balance.Coin:
      properties:
        success:
          type: string
          description: true or false
          example: true
        coin:
          type: array
          description: coin name
          items:
            properties:
              balance:
                type: string
                description: Balance in string format
                example: 10,000.00
              maintenance:
                type: string
                description: true or false
                example: true

    Deposit.Coin:
      properties:
        success:
          type: string
          description: true or false
          example: true
        coin:
          type: array
          description: coin name
          items:
            properties:
              deposit_address:
                type: string
                description: Deposit address
                example: >-
                  WrkzReo4ys8HFtoJkWvcEb9bSwQnXUDswAZqXR4A5cBa9PtYm4VS7Uz9w1WkuDquK1J6YXPGb3hrkHw15goxkeBHHxdBTLWnyRQb3X63R46gBBeuxBrgbRZ2qZLRf5TwnheZ1rpta1FAbR7XvMK6bL8Jkk293fJBL2ywDcHCXur4Z8VY59NBQcvwhB
              maintenance:
                type: string
                description: true or false
                example: true
